# Run JanusGraphExample in docker
# https://github.com/JanusGraph/janusgraph-docker
# docker-compose -f docker-compose-janusgraph.yml up
version: "3"

services:
  janusgraph:
    image: janusgraph/janusgraph:latest
    container_name: janusgraph-default
    ports:
    - "8182:8182"
    # The mounted volume only makes sense if JanusGraphExample is being run with the BerekeleyDB storage.
    volumes:
    - "janusgraph-default-data:/var/lib/janusgraph"

volumes:
  janusgraph-default-data: